import pika
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv

load_dotenv()

# AMQP connection settings
AMQP_URL = os.getenv("AMQP_URL")
QUEUE_NAME = os.getenv("QUEUE_NAME")

# SendGrid SMTP settings
SENDGRID_SMTP = os.getenv("SENDGRID_SMTP")
SENDGRID_PORT = int(os.getenv("SENDGRID_PORT", 465))  # Default to 465 if not set
SENDGRID_USER = os.getenv("SENDGRID_USER")
SENDGRID_PASSWORD = os.getenv("SENDGRID_PASSWORD")
EMAIL_FROM = os.getenv("EMAIL_FROM")
EMAIL_TO = os.getenv("EMAIL_TO")         # Comma-separated or list or None
EMAIL_TO_CC = os.getenv("EMAIL_TO_CC")   # Comma-separated or list or None
EMAIL_TO_BCC = os.getenv("EMAIL_TO_BCC") # Comma-separated or list or None

def parse_recipients(recipients):
    if recipients is None:
        return []
    if isinstance(recipients, str):
        # Split by comma, strip whitespace and unwanted characters like quotes/brackets
        recipients = [r.strip().strip('[]"\'') for r in recipients.split(",") if r.strip()]
    elif isinstance(recipients, list):
        recipients = [r.strip().strip('[]"\'') for r in recipients if r and r.strip()]
    else:
        recipients = []
    return recipients

def get_queue_message_count():
    params = pika.URLParameters(AMQP_URL)
    connection = pika.BlockingConnection(params)
    channel = connection.channel()
    queue = channel.queue_declare(queue=QUEUE_NAME, passive=True)
    message_count = queue.method.message_count
    connection.close()
    return message_count

def send_email_alert(queue_length):
    subject = f"CloudAMQP ALERT: {QUEUE_NAME} has {queue_length} items"
    html_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif;">
            <div>
                Hi Team,
                <br/>
                <br/>
                This script runs every 10 minutes and notifies you when more than or equal to 10 items are in the queue.
            </div>
            <div>
                <p>Queue:<b> {QUEUE_NAME}</b> currently has <span style="color:red; font-weight:bold;">{queue_length}</span> items.</p>
                <p>This may indicate the queue is stuck.<br>
                <br>
                Please review the Heroku and CloudAMQP dashboard to investigate promptly.</p>
                <p
                  style="margin-bottom:4px;">Thanks,<br>
                   Engineering Team</p>
                <small>This is an automated email generated by the Queue Monitoring system.</small>
            </div>
        </body>
    </html>
    """

    # Parse recipients robustly
    to_addrs = parse_recipients(EMAIL_TO)
    cc_addrs = parse_recipients(EMAIL_TO_CC)
    bcc_addrs = parse_recipients(EMAIL_TO_BCC)

    # Compose the email message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = EMAIL_FROM
    msg['To'] = ", ".join(to_addrs) if to_addrs else ""
    if cc_addrs:
        msg['Cc'] = ", ".join(cc_addrs)
    # BCC is not added to headers for privacy

    msg.attach(MIMEText(html_body, "html"))

    all_recipients = to_addrs + cc_addrs + bcc_addrs
    print(f"Sending email to: {all_recipients}")
    print(f"Sending email to cc_addrs: {cc_addrs}")


    if all_recipients:
        with smtplib.SMTP_SSL(SENDGRID_SMTP, SENDGRID_PORT) as server:
            server.login(SENDGRID_USER, SENDGRID_PASSWORD)
            server.sendmail(EMAIL_FROM, all_recipients, msg.as_string())
    else:
        print("No valid email recipients provided. Email not sent.")

if __name__ == "__main__":
    queue_length = get_queue_message_count()
    print(f"Queue '{QUEUE_NAME}' has {queue_length} messages.")
    if queue_length >= 5 :
        send_email_alert(queue_length)
        print("Alert sent.")
